### ISSUE TITLE
Unclear error message

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pbs#36]
After updating PyBossa I suppose I forgot to also update the database, so when later trying to create a project via pbs I get `pbsexceptions.ProjectNotFound: PyBossa Project not found`, when in fact the problem is a database error.

Actual response:

```
{u'status': u'failed', u'target': u'project', u'exception_msg': u'(psycopg2.ProgrammingError) relation "project_stats" does not exist\nLINE 1: INSERT INTO project_stats \n                    ^\n', u'status_code': 500, u'exception_cls': u'ProgrammingError', u'action': u'POST'}
```

So, maybe putting another check into `check_api_error` would be useful!

**Comment by teleyinex** [comment]
Yes, the error reporting should be MUCH better. Our bad. 
![bitmoji](https://render.bitstrips.com/v2/cpanel/9176152-264929344_5-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by alexandermendes** [comment]
No worries :smile: It just had me confused for a while! Admittedly 'DatabaseError' isn't a very clear message either but perhaps OK temporarily.

**Comment by teleyinex** [comment]
Better than what we have :D
